behaviors:
  Hallway:
    trainer_type: sac
    hyperparameters:
      learning_rate:
        opt_values: [0.001, 0.0003]
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 200000
      buffer_init_steps: 
        opt_values: [0, 2000]
      tau: 
        opt_values: [0.005, 0.008]
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: 
        opt_values: [simple, resnet]
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 10000
